name: "stable-release"

on:
  push:
    branches:
      - 'stable'

jobs:
  ubunut20:
    name: "ubuntu compile and test"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1          
      - uses: BSFishy/meson-build@v1.0.2
        name: build full
        with:
          action: build
          directory: build
          options: --verbose
          meson-version: 0.61.3
      - name: clearing build directory
        run: rm -rf build

  windows:
    name: "windows compile and test"
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v1
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            base-devel
            mingw-w64-x86_64-python3
            mingw-w64-x86_64-meson
      - name: compile rs232 lib 
        shell: msys2 {0}
        run: |
          meson setup  -Ddefault_library=static -Db_lto=true -Db_pgo=off build
          meson compile -C build
          meson test -C build
      - name: clearing build directory
        run: Remove-Item -recurse -force build
        
  macos:
    name: "mac os compile and test"
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1                
      - uses: BSFishy/meson-build@v1.0.2
        name: build full
        with:
          action: build
          directory: build
          options: --verbose
          meson-version: 0.61.3
      - name: clearing build directory
        run: rm -rf build

  stable-release:
    name: "Release candidate"
    runs-on: "ubuntu-20.04"
    needs: [windows, ubunut20, macos]
    steps:
      - uses: actions/checkout@v1
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "stable"
          prerelease: false
          title: "stable Build"
          files: |
            LICENSE
            
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: build-artifact-${{ matrix.os }}-${{ matrix.compiler }}
          path: .
